#pragma once

#define MAIXDUINO_D0_PIN 4
#define MAIXDUINO_D1_PIN 5
#define MAIXDUINO_D2_PIN 21
#define MAIXDUINO_D3_PIN 22
#define MAIXDUINO_D4_PIN 23
#define MAIXDUINO_D5_PIN 24
#define MAIXDUINO_D6_PIN 32
#define MAIXDUINO_D7_PIN 15
#define MAIXDUINO_D8_PIN 14
#define MAIXDUINO_D9_PIN 13
#define MAIXDUINO_D10_PIN 12
#define MAIXDUINO_D11_PIN 11
#define MAIXDUINO_D12_PIN 10
#define MAIXDUINO_D13_PIN 3
#define MAIXDUINO_SCL_PIN 30
#define MAIXDUINO_SDA_PIN 31

#define MAIXDUINO_SD_SCLK_PIN 27
#define MAIXDUINO_SD_MOSI_PIN 28
#define MAIXDUINO_SD_MISO_PIN 26
#define MAIXDUINO_SD_CS_PIN 29